<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Keyboard and mouse</title>
    <link rel="stylesheet" href="style.css">
</head>
<body class="">
    <div class="main"><div class="icon">
        <h2 class="logo">Shobi's<span>Laptop</span></h2>
        </div>
                <div class="navbar">
                    <div class="menu">
                            <ul>
                            <li><a href="/index.php">Home</a></li>
                            <li><div class="dropdown">
                            <button class="dropbtn">Shop by brands</button>
                            <div class="dropdown-content">
                              <a href="/ACER/ACER.PHP">Acer</a>
                              <a href="/ASUS/ASUS.PHP">Asus</a>
                              <a href="/DELL/DELL.PHP">Dell</a>
                            </div></li>
                            
                            <li><div class="dropdown">
                              <button class="dropbtn">Peripherals</button>
                            <div class="dropdown-content">
                                <a href="#">Keyboard and mouse</a>
                                <a href="/HDD_SSD/HDDSSD.PHP">External HDD and SSD</a>
                                <a href="/MONITOR_HEADSET/MONITOR_HEADSET.PHP">Monitor and Headset</a>
                                <a href="/SOFTWARE/SOFTWARE.PHP">Softwares</a>
                                </div></li>
                            <li><a href="/contact.php">Contact Us</a></li>
                            <li><a href="/AboutUs.php">About Us</a></li>
                        </ul>
                   
                    </div>
                    
                </div>
                <br>
              
    <div class="container"> <!--acer-->
        <header>
            <h1 class="brand">Available keyboard and mouse products</h1>
            <div class="shopping">
                <img src="cart.png">
                <span class="quantity">0</span>
            </div>
        </header>
    <div class="list"> </div>
    </div>
    <div class="card">
        <h1>My Cart</h1>
        <div class="listCard"></div>
        <div class="checkOut">
            <div class="total">0</div>
            <div class="closeShopping">Close</div>
        </div>
    </div>

    <script src="app.js"></script>
</body>
</html>