<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="carreers.css">
    <title>Carreers</title>
</head>
<body>
    <div class="main"><div class="icon">
        <h2 class="logo">Shobi's<span>Laptop</span></h2>
        </div>
                <div class="navbar">
                    <div class="menu">
                        <ul>
                            <li><a href="/index.php">Home</a></li>
                            <li><div class="dropdown">
                            <button class="dropbtn">Shop by brands</button>
                                <div class="dropdown-content">
                                 <a href="/ACER/ACER.PHP">Acer</a>
                                 <a href="/ASUS/ASUS.PHP">Asus</a>
                                 <a href="/DELL/DELL.PHP">Dell</a>
                                </div></li>
                            
                            <li><div class="dropdown">
                                <button class="dropbtn">Peripherals</button>
                                <div class="dropdown-content">
                                  <a href="/KEYBOARD AND MOUSE/KEYBOARD_MOUSE.php">Keyboard and mouse</a>
                                  <a href="/HDD_SSD/HDDSSD.PHP">External HDD and SSD</a>
                                  <a href="/MONITOR AND HEADSET/MONITOR_HEADSET.php">Monitor and Headset</a>
                                  <a href="/SOFTWARE/SOFTWARE.PHP">Softwares</a>
                                </div></li>
                            <li><a href="/contact.php">Contact Us</a></li>
                            <li><a href="/AboutUs.php">About Us</a></li>
                        </ul>
                        </div>
                      <br>  
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <img src="carreerbanner.webp" alt="" style="width:90%;">
                </div>
</body>
</html>